### ISSUE TITLE
VigoBus en Homeassistant

### ISSUE THREAD

**Issue by Thundervf** [David-Lor/Python_VigoBusAPI#29]
Hola, me gustaría saber si existe posibilidad de que la app pueda ser integrada en Homeassistant mediante HACS. Esto con el fin de poder visualizar en el lovelace de HA las tarjetas en tiempo real de determinadas paradas de buses. Gracias de antemano.

**Comment by David-Lor** [comment]
Buenas! Pues justamente hace no mucho se me había pasado por la cabeza hacer algo así... pero es solo una idea, dudo mucho que llegue a llevarlo a cabo.

Opciones que habría de cara a desarrollar un plugin para HomeAssistant: desplegar en local la VigoBusAPI y desarrollar el plugin, que básicamente tendría que hacer peticiones GET contra el servidor.

Si no se quiere desarrollar un plugin, igual se puede hacer alguna "chapucilla" metiendo algún script dentro del propio HomeAssistant que haga esas requests y actualice variables tipo "ayudante" del propio HA con los buses que pasan, aunque no sé qué tal se vería luego en la interfaz.

Por otra parte, tengo en curso (pero la cosa va bastante despacio) hacer un refactor total de la VigoBusAPI, todavía no lo tengo del todo decidido, pero estaba pensando en convertir el proyecto en más bien una librería Python que se pudiese importar en otros proyectos. De forma que no tenga que depender obligatoriamente de un MongoDB y todas esas historias (y quizás volver a hacer del VigoBusBot un monolito 🗿)

**Comment by Thundervf** [comment]
Gracias por tu respuesta. Pues sería de gran utilidad (aunque fuera chapuza jejeje) que se pudiera tener en HA. Obviamente el porcentaje de personas que lo usarían sería algo mínimo en comparación al VigoBus Bot de Telegram claro está... Pero para los que queremos tener lo máximo posible integrado en HA, vendría de lujo. O de pronto que existiera algo en web, de tal manera de usar la web page card del lovelace de HA y tener varias tarjetas de esas como recuadros por cada ID de Parada que uno necesite visualizar.

**Comment by David-Lor** [comment]
Bueno, si te sirve una interfaz web, igual puedes tirar de la "oficial" :stuck_out_tongue_winking_eye:  a ver qué tal se ve en la web page card:

http://infobus.vitrasa.es:8002/Default.aspx?parada=5800

(esta página es adonde llevan los QR que hay en las paradas)

**Comment by Thundervf** [comment]
Gracias por el dato, sin embargo al tener mi HA securizado (ssl) no deja añadir enlaces webs que no sean https, y en este caso, dicha web no tiene ssl :-/. Tendré que buscar a ver de que manera la puedo añadir.

**Comment by Thundervf** [comment]
Así es como queda con las web page card en HA. Solo que como los enlaces son htttp y no https, no puedo ver esas tarjetas fuera de mi red local.
![Sin título](https://github.com/David-Lor/VigoBusAPI/assets/120726842/90f05f7d-4c90-4737-a731-d619f5e6422c)
